from meu_grafo_lista_adj_nao_dir import MeuGrafo
pb = MeuGrafo()
pb.adiciona_vertice('J')
pb.adiciona_vertice('C')
pb.adiciona_vertice('E')
pb.adiciona_vertice('P')
pb.adiciona_vertice('M')
pb.adiciona_vertice('T')
pb.adiciona_vertice('Z')
pb.adiciona_aresta('a1','J','C', 2)
pb.adiciona_aresta('a2','C','E', 2)
pb.adiciona_aresta('a3','C','E', 3)
pb.adiciona_aresta('a4','C','P', 6)
pb.adiciona_aresta('a5','C','P', 7)
pb.adiciona_aresta('a6','C','M', 8)
pb.adiciona_aresta('a7','C','T', 9)
pb.adiciona_aresta('a8','M','T', 10)
pb.adiciona_aresta('a9','T','Z', 11)
print(pb.ha_laco())

